name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore
      run: dotnet restore
      working-directory: .

    - name: Build
      run: dotnet build -c Release -f:net9.0-windows10.0.19041.0
      working-directory: .

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: .

    - name: Code Analysis
      run: dotnet format ./AppVersioning.sln
      working-directory: .

    - name: Verify Code Analysis
      run: dotnet format --verify-no-changes ./AppVersioning.sln
      working-directory: .

    - name: Lint Code
      run: npm run lint
      working-directory: .
      env:
        NODE_ENV: development
